### Create a new Patient entity
POST http://localhost:8080/patients
Content-Type: application/json


{
    "name": "Gaurav jain",
    "email": "gaurav.jain@example.com",
    "address": "1234 Elm St, Springfield, IL 62704",
    "dateOfBirth": "1990-05-15",
    "registeredDate": "2023-04-01"
}

###